### ISSUE TITLE
Bug: Mauri e' piciu

### ISSUE THREAD

**Issue by karimone** [mauri1982/provaLektor#1]

**Comment by mauri1982** [comment]
premesso che:
1- avevo un lavoro che ho mollato per venire a figa in russia
2-ho trovato lavoro nel sud italia dalla russia
3-guadagno piu di prima
4-scopo meno di prima
tutto questo non ha un porcoddio di senso

PROBLEMA PICIU 1
### where is:
template>navbar.html
### explanation issue
nelle righe 22/44 c'è il menu classico in html con le classi di bootstrap
ho provato a sostituirlo dalla riga 45 con il ciclo di jinja, ma non ho idea di come inserire il sottomenu (classe dropdown di bootstrap)

PROBLEMA PICIU 2
### where is:
template>about.html
### explanation issue
riga 40, nell'aside, menu laterale. perche non mi considera lo stato a active?

idem nel menu breadcrumb, riga 54. in la pagina attuale (quindi lo stato active) non dovrebbe essere un link.

comunque fa con comodo... sto incasinatissimo non c'è fretta.
possiamo anche vederlo assieme nei prossimi giorni se preferisci.

<3

**Comment by karimone** [comment]
mai mettere piu' issue in un thread solo.
